import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  overlays: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(238, 253, 240, 0.8)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    width: "100%",
    backgroundColor: "#C2E7B0",
    padding: 20,
    elevation: 3,
    marginBottom: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginLeft: 14,
    color: '#333',
    marginTop: '8%',
    marginLeft: '18%',
  },
    backArrowContainer: {
    position: 'absolute',
    top: 40,
    left: 22,
    zIndex: 10,
    width: 40, 
    height: 40, 
    borderRadius: 20, 
    justifyContent: 'center', 
    alignItems: 'center', 
    borderWidth: 2, 
    borderColor: '#000', 
  },
  backButton: {
    fontSize: 24, 
    color: 'black',
    fontWeight: 'bold',
    textAlign: 'center', 
    lineHeight: 24, 
  },
  messagesList: {
    flex: 1,
    padding: 10,
  },
  notificationContainer: {
    backgroundColor: 'rgba(219, 252, 215, 0.5)',
    padding: 10,
    borderRadius: 8,
    marginVertical: 5,
    alignSelf: 'center',
    maxWidth: '90%',
    marginBottom: 15,
  },
  notificationText: {
    color: 'rgb(1, 60, 1)',
    fontSize: 14,
    textAlign: 'center',
  },
  suggestionContainer: {
    backgroundColor: 'rgba(226, 226, 226, 0.8)',
    padding: 15,
    borderRadius: 12,
    marginVertical: 5,
    maxWidth: '85%',
    alignSelf: 'flex-start',
  },
  suggestionText: {
    color: '#666',
    fontSize: 14,
    lineHeight: 24,
  },
  messageContainer: {
    maxWidth: '85%',
    padding: 15,
    borderRadius: 12,
    marginVertical: 5,
  },
  userMessageContainer: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgb(239, 249, 214)',
    borderWidth: 2,
    borderColor: 'rgb(0, 60, 22)',
    marginBottom: 15,
  },
  botMessageContainer: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgb(243, 251, 235)',
    borderWidth: 2,
    borderColor: 'rgb(0, 60, 22)',
    marginBottom: 15,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 24,
  },
  userMessageText: {
    color: 'rgb(0, 60, 22)',
  },
  botMessageText: {
    color: 'black',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    backgroundColor: '#C2E7B0',
  },
  input: {
    flex: 1,
    backgroundColor: 'rgb(243, 251, 235)',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 16,
    borderWidth: 1.5,
    borderColor: 'rgb(0, 60, 22)',
    marginRight: 10,
    maxHeight: 100,
  },
  sendIcon: {
    color: 'rgb(0, 60, 22)',
    fontSize: 32,
    marginHorizontal: 5,
    marginBottom: 5,
  },

  languageButtonContainer: {
    width: 25,
    height: 25,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: -20,
    marginLeft: 155,
    flexDirection: 'row', 
  },

  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'rgb(238, 248, 229)',
    borderRadius: 20,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    borderStyle: 'solid',
    borderColor: 'rgb(1, 80, 0)',
    borderWidth: 2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
  },
  languageButton: {
    width: '100%',
    padding: 15,
    borderRadius: 25,
    marginBottom: 10,
    borderStyle: 'solid',
    borderColor: 'rgb(1, 80, 0)',
    borderWidth: 2,
    backgroundColor: 'rgb(247, 254, 230)',
  },
  selectedLanguage: {
    borderStyle: 'solid',
    borderColor: 'rgb(1, 80, 0)',
    borderWidth: 2,
    backgroundColor: 'rgb(238, 254, 201)',
  },
  languageText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#333',
  },
  closeButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: 'rgb(1, 65, 7)',
    borderRadius: 25,
    width: '70%',
  },
  closeButtonText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.8,
    fontWeight: 'bold',
  },
  questionButton: {
    padding: 5,
    marginTop: 5,
    marginBottom: 5,
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  questionButtonText: {
    color: 'rgb(90, 89, 89)',
    fontSize: 14,
  }

});

export default styles;
