// Styles/DiagnosisStyles.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgb(238, 248, 229)',
  },
  
  backgroundImage: {
    flex: 1,
    width: '100%',
  },
  overlays: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
  },
 header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      width: "100%",
      backgroundColor: "#C2E7B0",
      padding: 20,
      elevation: 3,
      marginBottom: 10,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '600',
      marginLeft: 14,
      color: '#333',
      marginTop: '8%',
      marginLeft: '18%',
    },
  backArrowContainer: {
      position: 'absolute',
      top: 40,
      left: 22,
      zIndex: 10,
      width: 40, 
      height: 40, 
      borderRadius: 20, 
      justifyContent: 'center', 
      alignItems: 'center', 
      borderWidth: 2, 
      borderColor: '#000', 
    },
    backButton: {
      fontSize: 24, 
      color: 'black',
      fontWeight: 'bold',
      textAlign: 'center', 
      lineHeight: 24
    },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  imageContainer: {
    alignItems: 'center',
    padding: 20,
    marginBottom: 10,
  },
  image: {
    width: 300,
    height: 200,
    borderRadius: 10,
    backgroundColor: '#eee',
  },
  noImagePlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  noImageText: {
    marginTop: 10,
    color: '#999',
  },
  resultContainer: {
    backgroundColor: 'rgb(238, 248, 229)',
    borderRadius: 15,
    margin: 15,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  diagnosisTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 15,
  },
  confidenceContainer: {
    marginBottom: 20,
  },
  confidenceText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 5,
  },
  confidenceBar: {
    height: 10,
    backgroundColor: 'rgb(151, 165, 162)',
    borderRadius: 5,
    overflow: 'hidden',
  },
  confidenceFill: {
    height: '100%',
    borderRadius: 5,
  },
  highConfidence: {
    backgroundColor: 'rgb(5, 71, 3)',
  },
  lowConfidence: {
    backgroundColor: '#F44336',
  },
  infoSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'rgb(0, 60, 22)',
    marginBottom: 10,
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#555',
    marginTop: 15,
    marginBottom: 10,
  },
  sectionText: {
    fontSize: 15,
    color: '#444',
    lineHeight: 22,
  },
  symptomItem: {
    flexDirection: 'row',
    marginBottom: 5,
    paddingRight: 10,
  },
  bulletPoint: {
    marginRight: 8,
    color: 'rgb(0, 60, 22)',
    fontSize: 16,
  },
  symptomText: {
    flex: 1,
    fontSize: 15,
    color: '#444',
    lineHeight: 20,
  },
  takeAnotherButton: {
    backgroundColor: 'rgb(0, 60, 22)',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
    alignSelf: 'center',
    marginVertical: 20,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  notTeaContainer: {
    backgroundColor: 'white',
    borderRadius: 15,
    margin: 15,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  notTeaTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ff6b6b',
    marginVertical: 10,
  },
  notTeaDescription: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 15,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    color: '#666',
    fontSize: 16,
  },
  errorText: {
    fontSize: 16,
    color: '#ff6b6b',
    padding: 20,
    textAlign: 'center',
  },
  // New styles for the action buttons
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 15,
    marginBottom: 20,
  },
  actionButton: {
    backgroundColor: 'rgb(0, 60, 22)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '45%',
  },
  actionButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    borderWidth: 2,
    borderColor: 'rgb(0, 60, 22)',
    backgroundColor: 'rgb(238, 248, 229)',
    borderRadius: 17,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eaeaea',
    paddingBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  languageOption: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eaeaea',
  },
  languageOptionSelected: {
    borderRadius: 30,
    backgroundColor: 'rgba(133, 127, 123, 0.1)',
  },
  languageName: {
    paddingLeft: 10, 
    fontSize: 16,
    color: '#333',
  },
});

export default styles;