import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(238, 253, 240, 0.4)',
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  overlays: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(238, 249, 253, 0.82)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    width: '100%',
    backgroundColor: 'rgba(135, 204, 230, 0.82)',
    padding: 20,
    elevation: 3,
    marginBottom: 10,
  },
  scrollView: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    marginLeft: '18%',
    color: '#333',
    marginTop: '8%',
  },
  backArrowContainer: {
      position: 'absolute',
      top: 40,
      left: 22,
      zIndex: 10,
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#000',
  },
  backButton: {
      fontSize: 24,
      color: 'black',
      fontWeight: 'bold',
      textAlign: 'center',
      lineHeight: 24,
  },
  topic: {
    fontSize: 20,
    justifyContent: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
    marginTop: 160,
  },
  newPasswordContainer: {
    width: '90%',
    height: 60,
    backgroundColor: 'rgba(230, 243, 247, 0.8)',
    borderRadius: 15,
    paddingHorizontal: 15,
    marginVertical: 10,
    borderWidth: 1.5,
    borderColor: 'rgb(0, 0, 0)',
    marginLeft: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  confirmPasswordContainer: {
    width: '90%',
    height: 60,
    backgroundColor: 'rgba(230, 243, 247, 0.8)',
    borderRadius: 15,
    paddingHorizontal: 15,
    marginVertical: 10,
    borderWidth: 1.5,
    borderColor: 'rgb(0, 0, 0)',
    marginLeft: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputPassword: {
    flex: 1,
    fontSize: 14,
  },
  eyeIcon: {
    marginLeft: 10,
  },
  button: {
    width: '50%',
    height: 50,
    backgroundColor: 'rgba(135, 204, 230, 0.82)',
    borderRadius: 25,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginLeft: 97,
    marginTop: 40,
    borderWidth: 1.5,
    borderColor: 'rgb(0, 0, 0)',
  },
  buttonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  message: {
    marginTop: 16,
    fontSize: 16,
    color: 'green',
  },
  input: {
    width: "90%",
    borderBottomWidth: 1,
    borderBottomColor: "rgb(141, 142, 142)",
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 14,
  },
  errorText: {
    color: 'red',
    marginHorizontal: 20,
    marginBottom: 15,
    fontSize: 14,
  },
  hintText: {
    color: '#000',
    marginHorizontal: 20,
    marginBottom: 20,
    fontSize: 12,
    fontStyle: 'italic',
  },
});

export default styles;
