import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: 'rgba(238, 253, 240, 0.4)',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      width: "100%",
      backgroundColor: "#C2E7B0",
      padding: 20,
      elevation: 3,
      marginBottom: 10,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '600',
      marginLeft: 14,
      color: '#333',
      marginTop: '8%',
      marginLeft: '18%',
    },
    scrollContent: {
      flex: 1,
    },
    backgroundImage: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      flex: 1,
      resizeMode: 'cover',
    },
    contentContainer: {
      padding: 16,
    },
    stepCard: {
      marginBottom: 24,
      backgroundColor: "rgb(238, 248, 229)",
      borderRadius: 15,
      marginHorizontal: 15,
      padding: 15,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
      borderWidth: 1.8,
      borderColor: 'rgb(0, 60, 22)',
    },
    stepImage: {
      width: '100%',
      height: 160,
      resizeMode: 'cover',
    },
    overlays: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(238, 253, 240, 0.8)',
    },
    stepInfo: {
      padding: 16,
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    stepNumber: {
      fontSize: 14,
      fontWeight: 'bold',
      marginLeft: 6,
      color: '#666',
    },
    backArrowContainer: {
      position: 'absolute',
      top: 40,
      left: 22,
      zIndex: 10,
      width: 40, 
      height: 40, 
      borderRadius: 20, 
      justifyContent: 'center', 
      alignItems: 'center', 
      borderWidth: 2, 
      borderColor: '#000', 
    },
    backButton: {
      fontSize: 24, 
      color: 'black',
      fontWeight: 'bold',
      textAlign: 'center', 
      lineHeight: 24
    },
    stepTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 8,
      color: '#333',
    },
    stepDescription: {
      fontSize: 14,
      color: '#666',
      lineHeight: 20,
    },
    actionContainer: {
      marginTop: 16,
      marginBottom: 80,
    },
    primaryButton: {
      backgroundColor: 'rgb(0, 60, 22)',
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: 'center',
      marginBottom: 12,
    },
    primaryButtonText: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 16,
    },
    bottomNavBar: {
      flexDirection: 'row',
      backgroundColor: 'white',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingVertical: 10,
      justifyContent: 'space-around',
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      backgroundColor: "#C2E7B0",
    },
    navItem: {
      alignItems: 'center',
      padding: 8,
      
    },
    activeNavItem: {
      backgroundColor: '#E8F5E9',
      borderRadius: 20,
      paddingHorizontal: 20,
    },
    navText: {
      fontSize: 12,
      marginTop: 4,
      color: '#666',
    },
    activeNavText: {
      color: '#4CAF50',
      fontWeight: 'bold',
    },
});
export default styles;
  